language: android
android:
  components:
    - build-tools-18.1.0
    - platform-tools
before_install:
  - "npm install phonegap"
before_script:
  - "android update project --path platforms/android/ --subprojects"
script:
  - "phonegap build android"
after_script:
  - "mv platforms/android/ant-build/Discounter-debug.apk Discounter.apk"
  - "rm -rf hooks node_modules platforms plugins README.md www"
  - "chmod +x s3.sh"
  - "./s3.sh upload Discounter.apk Discounter.apk"
