language: android
android:
  components:
    - build-tools-18.1.0
    - platform-tools
before_install:
  - "npm install phonegap"
  - "npm install cordova"
  - "phonegap install android"
script:
  - "phonegap build android && mv platforms/android/ant-build/Discounter-debug.apk Discounter.apk"
